-- =============================================================================
-- PE_ASSISTANT: Production Engineering AI Advisor
-- Script 02: Raw Data Tables — RAW_VOLVE schema
-- =============================================================================
-- Run after: 01_infrastructure.sql
-- Next step: Upload Volve data files to @PE_POC.RAW_VOLVE.DATA_STAGE
-- =============================================================================

USE SCHEMA PE_POC.RAW_VOLVE;

-- Daily production data (loaded from Volve production CSV)
CREATE OR REPLACE TRANSIENT TABLE PRODUCTION_DAILY (
    DATEPRD VARCHAR,
    WELL_BORE_CODE VARCHAR,
    NPD_WELL_BORE_CODE VARCHAR,
    NPD_WELL_BORE_NAME VARCHAR,
    NPD_FIELD_CODE VARCHAR,
    NPD_FIELD_NAME VARCHAR,
    NPD_FACILITY_CODE VARCHAR,
    NPD_FACILITY_NAME VARCHAR,
    ON_STREAM_HRS VARCHAR,
    AVG_DOWNHOLE_PRESSURE VARCHAR,
    AVG_DOWNHOLE_TEMPERATURE VARCHAR,
    AVG_DP_TUBING VARCHAR,
    AVG_ANNULUS_PRESS VARCHAR,
    AVG_CHOKE_SIZE_P VARCHAR,
    AVG_CHOKE_UOM VARCHAR,
    AVG_WHP_P VARCHAR,
    AVG_WHT_P VARCHAR,
    DP_CHOKE_SIZE VARCHAR,
    BORE_OIL_VOL VARCHAR,
    BORE_GAS_VOL VARCHAR,
    BORE_WAT_VOL VARCHAR,
    BORE_WI_VOL VARCHAR,
    FLOW_KIND VARCHAR,
    WELL_TYPE VARCHAR
);

-- Monthly production data
CREATE OR REPLACE TRANSIENT TABLE PRODUCTION_MONTHLY (
    DATEPRD VARCHAR,
    WELL_BORE_CODE VARCHAR,
    NPD_WELL_BORE_CODE VARCHAR,
    NPD_WELL_BORE_NAME VARCHAR,
    NPD_FIELD_NAME VARCHAR,
    ON_STREAM_HRS VARCHAR,
    BORE_OIL_VOL VARCHAR,
    BORE_GAS_VOL VARCHAR,
    BORE_WAT_VOL VARCHAR,
    BORE_WI_VOL VARCHAR
);

-- Well header (full NCS wellbore registry from SODIR FactPages)
CREATE OR REPLACE TRANSIENT TABLE WELL_HEADER (
    WLBWELLBORENAME VARCHAR, WLBWELLTYPE VARCHAR, WLBWELL VARCHAR,
    WLBDRILLINGOPERATOR VARCHAR, WLBPRODUCTIONLICENCE VARCHAR,
    WLBPURPOSE VARCHAR, WLBSTATUS VARCHAR, WLBCONTENT VARCHAR,
    WLBSUBSEA VARCHAR, WLBENTRYDATE VARCHAR, WLBCOMPLETIONDATE VARCHAR,
    WLBENTRYPREDRILLDATE VARCHAR, WLBCOMPPREDRILLDATE VARCHAR,
    WLBFIELD VARCHAR, WLBDRILLPERMIT VARCHAR, WLBDISCOVERY VARCHAR,
    WLBDISCOVERYWELLBORE VARCHAR, WLBBOTTOMHOLETEMPERATURE VARCHAR,
    WLBSITESURVEY VARCHAR, WLBSEISMICLOCATION VARCHAR,
    WLBMAXINCLATION VARCHAR, WLBKELLYBUSHELEVATION VARCHAR,
    WLBFINALVERTICALDEPTH VARCHAR, WLBTOTALDEPTH VARCHAR,
    WLBWATERDEPTH VARCHAR, WLBKICKOFFPOINT VARCHAR,
    WLBAGEATTD VARCHAR, WLBFORMATIONATTD VARCHAR,
    WLBMAINAREA VARCHAR, WLBDRILLINGFACILITY VARCHAR,
    WLBFACILITYTYPEDRILLING VARCHAR, WLBDRILLINGFACILITYFIXEDORMOVE VARCHAR,
    WLBPRODUCTIONFACILITY VARCHAR, WLBLICENSINGACTIVITY VARCHAR,
    WLBMULTILATERAL VARCHAR, WLBPURPOSEPLANNED VARCHAR,
    WLBCONTENTPLANNED VARCHAR, WLBENTRYYEAR VARCHAR,
    WLBCOMPLETIONYEAR VARCHAR, WLBRECLASSFROMWELLBORE VARCHAR,
    WLBREENTRYEXPLORATIONACTIVITY VARCHAR, WLBPLOTSYMBOL VARCHAR,
    WLBFORMATIONWITHHC1 VARCHAR, WLBAGEWITHHC1 VARCHAR,
    WLBFORMATIONWITHHC2 VARCHAR, WLBAGEWITHHC2 VARCHAR,
    WLBFORMATIONWITHHC3 VARCHAR, WLBAGEWITHHC3 VARCHAR,
    WLBDRILLINGDAYS VARCHAR, WLBREENTRY VARCHAR,
    WLBLICENCETARGETNAME VARCHAR, WLBPLUGGEDABANDONDATE VARCHAR,
    WLBPLUGGEDDATE VARCHAR, WLBGEODETICDATUM VARCHAR,
    WLBNSDEG VARCHAR, WLBNSMIN VARCHAR, WLBNSSEC VARCHAR, WLBNSCODE VARCHAR,
    WLBEWDEG VARCHAR, WLBEWMIN VARCHAR, WLBEWSEC VARCHAR, WLBEWCODE VARCHAR,
    WLBNSDECDEG VARCHAR, WLBEWDECDEG VARCHAR,
    WLBNSUTM VARCHAR, WLBEWUTM VARCHAR, WLBUTMZONE VARCHAR,
    WLBNAMEPART1 VARCHAR, WLBNAMEPART2 VARCHAR,
    WLBDISKOSWELLBORETYPE VARCHAR,
    WLBNAMEPART3 VARCHAR, WLBNAMEPART4 VARCHAR,
    WLBNAMEPART5 VARCHAR, WLBNAMEPART6 VARCHAR,
    WLBPRESSRELEASEURL VARCHAR, WLBFACTPAGEURL VARCHAR, WLBFACTMAPURL VARCHAR,
    WLBDISKOSWELLBORETYPE1 VARCHAR, WLBDISKOSWELLBOREPARENT VARCHAR,
    WLBWDSSQCDATE VARCHAR, WLBRELEASEDDATE VARCHAR, WLBDATERECLASS VARCHAR,
    WLBNPDIDWELLBORE VARCHAR, PRLNPDIDPRODLICENCETARGET VARCHAR,
    FCLNPDIDFACILITYPRODUCING VARCHAR, DSCNPDIDDISCOVERY VARCHAR,
    FLDNPDIDFIELD VARCHAR, FCLNPDIDFACILITYDRILLING VARCHAR,
    WLBNPDIDWELLBORERECLASS VARCHAR, PRLNPDIDPRODUCTIONLICENCE VARCHAR,
    WLBNPDIDSITESURVEY VARCHAR, WLBALIASNAME VARCHAR,
    WLBDATEUPDATED VARCHAR, WLBDATEUPDATEDMAX VARCHAR, DATESYNCNPD VARCHAR
);

-- LAS file headers (populated by LOAD_LAS_FILES procedure)
CREATE OR REPLACE TABLE LAS_HEADERS (
    LAS_FILE_ID NUMBER NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
    FILENAME VARCHAR NOT NULL,
    LAS_VERSION VARCHAR, WRAP VARCHAR,
    STRT FLOAT, STOP FLOAT, STEP FLOAT, NULL_VALUE FLOAT, STRT_UNIT VARCHAR,
    WELL_NAME VARCHAR, FIELD_NAME VARCHAR, COMPANY VARCHAR,
    LOCATION VARCHAR, COUNTY VARCHAR, STATE VARCHAR, COUNTRY VARCHAR,
    SERVICE_COMPANY VARCHAR, LOG_DATE VARCHAR, UWI VARCHAR, API_NUMBER VARCHAR,
    LATITUDE VARCHAR, LONGITUDE VARCHAR, SURFACE_X FLOAT, SURFACE_Y FLOAT,
    ELEVATION FLOAT, ELEVATION_TYPE VARCHAR, PERMANENT_DATUM VARCHAR,
    PARAMETERS VARIANT, OTHER_INFO VARCHAR,
    NUM_CURVES NUMBER, NUM_DATA_ROWS NUMBER,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (LAS_FILE_ID)
);

-- LAS curve definitions
CREATE OR REPLACE TABLE LAS_CURVES (
    LAS_CURVE_ID NUMBER NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
    LAS_FILE_ID NUMBER NOT NULL,
    CURVE_INDEX NUMBER NOT NULL,
    MNEMONIC VARCHAR NOT NULL,
    UNIT VARCHAR, API_CODE VARCHAR, DESCRIPTION VARCHAR,
    PRIMARY KEY (LAS_CURVE_ID)
);

-- LAS log data (normalized: file x depth x curve)
CREATE OR REPLACE TABLE LAS_LOG_DATA (
    LAS_FILE_ID NUMBER NOT NULL,
    DEPTH FLOAT NOT NULL,
    MNEMONIC VARCHAR NOT NULL,
    VALUE FLOAT
);

-- Filtered view of Volve wells with production data
CREATE OR REPLACE TRANSIENT TABLE WELL_HEADER_VOLVE_PRODUCTION AS
SELECT * FROM PE_POC.RAW_VOLVE.WELL_HEADER
WHERE WLBFIELD = 'VOLVE'
  AND WLBNPDIDWELLBORE IN (
    SELECT DISTINCT WELL_BORE_CODE FROM PE_POC.RAW_VOLVE.PRODUCTION_DAILY
    WHERE WELL_BORE_CODE IS NOT NULL
  );

-- =============================================================================
-- DATA LOADING INSTRUCTIONS
-- =============================================================================
-- 1. Download Volve production data from Equinor's open data portal
-- 2. Upload files to the DATA_STAGE:
--    PUT file:///path/to/Volve_production_daily.csv @PE_POC.RAW_VOLVE.DATA_STAGE;
--    PUT file:///path/to/Volve_production_monthly.csv @PE_POC.RAW_VOLVE.DATA_STAGE;
--    PUT file:///path/to/wellbore_exploration_all.csv @PE_POC.RAW_VOLVE.DATA_STAGE;
--    PUT file:///path/to/*.LAS @PE_POC.RAW_VOLVE.DATA_STAGE;
-- 3. Load CSV data:
--    COPY INTO PE_POC.RAW_VOLVE.PRODUCTION_DAILY
--      FROM @PE_POC.RAW_VOLVE.DATA_STAGE/Volve_production_daily.csv
--      FILE_FORMAT = PE_POC.RAW_VOLVE.CSV_FORMAT;
--    COPY INTO PE_POC.RAW_VOLVE.PRODUCTION_MONTHLY
--      FROM @PE_POC.RAW_VOLVE.DATA_STAGE/Volve_production_monthly.csv
--      FILE_FORMAT = PE_POC.RAW_VOLVE.CSV_FORMAT;
--    COPY INTO PE_POC.RAW_VOLVE.WELL_HEADER
--      FROM @PE_POC.RAW_VOLVE.DATA_STAGE/wellbore_exploration_all.csv
--      FILE_FORMAT = PE_POC.RAW_VOLVE.CSV_FORMAT;
-- 4. Load LAS files (run the procedure from 03_load_procedures.sql):
--    CALL PE_POC.RAW_VOLVE.LOAD_LAS_FILES();
