-- =============================================================================
-- PE_ASSISTANT: Production Engineering AI Advisor
-- Script 04: Curated Layer — Views, materialized tables, domain knowledge
-- =============================================================================
-- Run after: 03_load_procedures.sql + loading raw data
-- =============================================================================

USE SCHEMA PE_POC.CURATED;

-- ---------------------------------------------------------------------------
-- Curated well header (filtered to Volve production wells)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE WELL_HEADER AS
SELECT
    TRY_TO_NUMBER(w.WLBNPDIDWELLBORE) AS WELLBORE_CODE,
    w.WLBWELLBORENAME AS WELLBORE_NAME,
    w.WLBWELL AS WELL_NAME,
    w.WLBWELLTYPE AS WELL_TYPE,
    w.WLBPURPOSE AS PURPOSE,
    w.WLBSTATUS AS STATUS,
    w.WLBCONTENT AS CONTENT,
    w.WLBFIELD AS FIELD_NAME,
    w.WLBDRILLINGOPERATOR AS OPERATOR,
    w.WLBPRODUCTIONFACILITY AS FACILITY,
    TRY_TO_DATE(w.WLBENTRYDATE, 'DD.MM.YYYY') AS SPUD_DATE,
    TRY_TO_DATE(w.WLBCOMPLETIONDATE, 'DD.MM.YYYY') AS COMPLETION_DATE,
    TRY_TO_DOUBLE(w.WLBTOTALDEPTH) AS TOTAL_DEPTH_M,
    TRY_TO_DOUBLE(w.WLBFINALVERTICALDEPTH) AS TVD_M,
    TRY_TO_DOUBLE(w.WLBWATERDEPTH) AS WATER_DEPTH_M,
    TRY_TO_DOUBLE(w.WLBKELLYBUSHELEVATION) AS KB_ELEVATION_M,
    TRY_TO_DOUBLE(w.WLBNSDECDEG) AS LATITUDE,
    TRY_TO_DOUBLE(w.WLBEWDECDEG) AS LONGITUDE,
    w.WLBFORMATIONATTD AS FORMATION_AT_TD,
    w.WLBAGEATTD AS AGE_AT_TD,
    w.WLBDISKOSWELLBOREPARENT AS PARENT_WELLBORE
FROM PE_POC.RAW_VOLVE.WELL_HEADER w
WHERE w.WLBFIELD = 'VOLVE'
  AND w.WLBNPDIDWELLBORE IN (
    SELECT DISTINCT WELL_BORE_CODE
    FROM PE_POC.RAW_VOLVE.PRODUCTION_DAILY
    WHERE WELL_BORE_CODE IS NOT NULL
  );

-- ---------------------------------------------------------------------------
-- Curated daily production (with derived columns)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE PRODUCTION_DAILY AS
SELECT
    TRY_TO_DATE(r.DATEPRD, 'YYYY-MM-DD') AS PRODUCTION_DATE,
    TRY_TO_NUMBER(r.WELL_BORE_CODE) AS WELLBORE_CODE,
    r.NPD_WELL_BORE_NAME AS WELLBORE_NAME,
    r.NPD_FIELD_NAME AS FIELD_NAME,
    r.NPD_FACILITY_NAME AS FACILITY_NAME,
    r.WELL_TYPE,
    r.FLOW_KIND,
    TRY_TO_DOUBLE(r.ON_STREAM_HRS) AS ON_STREAM_HRS,
    TRY_TO_DOUBLE(r.AVG_CHOKE_SIZE_P) AS AVG_CHOKE_PCT,
    TRY_TO_DOUBLE(r.AVG_DOWNHOLE_PRESSURE) AS AVG_DHP_BARA,
    TRY_TO_DOUBLE(r.AVG_WHP_P) AS AVG_WHP_BARA,
    TRY_TO_DOUBLE(r.AVG_ANNULUS_PRESS) AS AVG_ANNULUS_PRESS_BARA,
    TRY_TO_DOUBLE(r.DP_CHOKE_SIZE) AS DP_CHOKE_BARA,
    TRY_TO_DOUBLE(r.AVG_DOWNHOLE_TEMPERATURE) AS AVG_DHT_DEGC,
    TRY_TO_DOUBLE(r.AVG_WHT_P) AS AVG_WHT_DEGC,
    TRY_TO_DOUBLE(r.BORE_OIL_VOL) AS OIL_VOL_SM3,
    TRY_TO_DOUBLE(r.BORE_GAS_VOL) AS GAS_VOL_SM3,
    TRY_TO_DOUBLE(r.BORE_WAT_VOL) AS WATER_VOL_SM3,
    TRY_TO_DOUBLE(r.BORE_WI_VOL) AS WATER_INJ_VOL_SM3,
    -- Derived: water cut = water / (oil + water)
    CASE
        WHEN TRY_TO_DOUBLE(r.BORE_OIL_VOL) + TRY_TO_DOUBLE(r.BORE_WAT_VOL) > 0
        THEN TRY_TO_DOUBLE(r.BORE_WAT_VOL) /
             (TRY_TO_DOUBLE(r.BORE_OIL_VOL) + TRY_TO_DOUBLE(r.BORE_WAT_VOL))
        ELSE NULL
    END AS WATER_CUT,
    -- Derived: GOR = gas / oil (sm3/sm3)
    CASE
        WHEN TRY_TO_DOUBLE(r.BORE_OIL_VOL) > 0
        THEN TRY_TO_DOUBLE(r.BORE_GAS_VOL) / TRY_TO_DOUBLE(r.BORE_OIL_VOL)
        ELSE NULL
    END AS GOR_SM3_SM3,
    -- Derived: drawdown = DHP - WHP (bara)
    CASE
        WHEN TRY_TO_DOUBLE(r.AVG_DOWNHOLE_PRESSURE) IS NOT NULL
             AND TRY_TO_DOUBLE(r.AVG_WHP_P) IS NOT NULL
        THEN TRY_TO_DOUBLE(r.AVG_DOWNHOLE_PRESSURE) - TRY_TO_DOUBLE(r.AVG_WHP_P)
        ELSE NULL
    END AS DRAWDOWN_BARA,
    -- Derived: well status
    CASE
        WHEN TRY_TO_DOUBLE(r.ON_STREAM_HRS) > 0
             AND (TRY_TO_DOUBLE(r.BORE_OIL_VOL) > 0 OR TRY_TO_DOUBLE(r.BORE_GAS_VOL) > 0)
        THEN 'PRODUCING'
        WHEN TRY_TO_DOUBLE(r.BORE_WI_VOL) > 0 THEN 'INJECTING'
        ELSE 'SHUT-IN'
    END AS WELL_STATUS
FROM PE_POC.RAW_VOLVE.PRODUCTION_DAILY r;

-- ---------------------------------------------------------------------------
-- Petrophysics: pivot LAS log data into columnar format
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW PETROPHYSICS_LOGS AS
SELECT
    h.WELL_NAME AS WELLBORE_NAME,
    h.FIELD_NAME,
    d.DEPTH AS MEASURED_DEPTH_M,
    MAX(CASE WHEN d.MNEMONIC = 'PHIF' THEN d.VALUE END) AS POROSITY,
    MAX(CASE WHEN d.MNEMONIC = 'SW' THEN d.VALUE END) AS WATER_SATURATION,
    MAX(CASE WHEN d.MNEMONIC = 'VSH' THEN d.VALUE END) AS SHALE_VOLUME,
    MAX(CASE WHEN d.MNEMONIC = 'KLOGH' THEN d.VALUE END) AS PERMEABILITY_MD,
    MAX(CASE WHEN d.MNEMONIC = 'BVW' THEN d.VALUE END) AS BULK_VOLUME_WATER,
    MAX(CASE WHEN d.MNEMONIC = 'VCARB' THEN d.VALUE END) AS CARBONATE_VOLUME,
    MAX(CASE WHEN d.MNEMONIC = 'COAL_FLAG' THEN d.VALUE END) AS COAL_FLAG,
    MAX(CASE WHEN d.MNEMONIC = 'SAND_FLAG' THEN d.VALUE END) AS SAND_FLAG,
    MAX(CASE WHEN d.MNEMONIC = 'CARB_FLAG' THEN d.VALUE END) AS CARB_FLAG,
    1.0 - MAX(CASE WHEN d.MNEMONIC = 'SW' THEN d.VALUE END) AS HC_SATURATION,
    CASE WHEN MAX(CASE WHEN d.MNEMONIC = 'VSH' THEN d.VALUE END) < 0.5
              AND MAX(CASE WHEN d.MNEMONIC = 'PHIF' THEN d.VALUE END) > 0.08
         THEN 1 ELSE 0 END AS NET_FLAG
FROM PE_POC.RAW_VOLVE.LAS_LOG_DATA d
JOIN PE_POC.RAW_VOLVE.LAS_HEADERS h ON d.LAS_FILE_ID = h.LAS_FILE_ID
GROUP BY h.WELL_NAME, h.FIELD_NAME, d.DEPTH;

-- Materialize for performance
CREATE OR REPLACE TABLE PETROPHYSICS_LOGS_TABLE AS
SELECT * FROM PETROPHYSICS_LOGS;

-- Per-well summary
CREATE OR REPLACE VIEW PETROPHYSICS_WELL_SUMMARY AS
SELECT
    WELLBORE_NAME,
    COUNT(*) AS TOTAL_SAMPLES,
    SUM(NET_FLAG) AS NET_SAMPLES,
    ROUND(SUM(NET_FLAG)::FLOAT / NULLIF(COUNT(*), 0), 3) AS NET_TO_GROSS,
    MIN(MEASURED_DEPTH_M) AS MIN_DEPTH_M,
    MAX(MEASURED_DEPTH_M) AS MAX_DEPTH_M,
    ROUND(AVG(CASE WHEN NET_FLAG = 1 THEN POROSITY END), 4) AS AVG_POROSITY_NET,
    ROUND(AVG(CASE WHEN NET_FLAG = 1 THEN WATER_SATURATION END), 4) AS AVG_SW_NET,
    ROUND(AVG(CASE WHEN NET_FLAG = 1 THEN SHALE_VOLUME END), 4) AS AVG_VSH_NET,
    ROUND(AVG(CASE WHEN NET_FLAG = 1 THEN PERMEABILITY_MD END), 4) AS AVG_PERM_NET_MD,
    ROUND(MAX(CASE WHEN NET_FLAG = 1 THEN PERMEABILITY_MD END), 4) AS MAX_PERM_NET_MD,
    ROUND(AVG(CASE WHEN NET_FLAG = 1 THEN HC_SATURATION END), 4) AS AVG_HC_SAT_NET
FROM PE_POC.CURATED.PETROPHYSICS_LOGS
GROUP BY WELLBORE_NAME;

-- Materialize
CREATE OR REPLACE TABLE PETROPHYSICS_WELL_SUMMARY_TABLE AS
SELECT * FROM PETROPHYSICS_WELL_SUMMARY;

-- ---------------------------------------------------------------------------
-- Domain Knowledge table (vocabulary resolution for the agent)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE PRODUCTION_DOMAIN_KNOWLEDGE (
    ENTRY_ID VARCHAR NOT NULL DEFAULT UUID_STRING(),
    ENTRY_TYPE VARCHAR NOT NULL
        COMMENT 'SYNONYM | RULE | METRIC | PATTERN | COLUMN_DESC | TABLE_DESC',
    CATEGORY VARCHAR COMMENT 'Sub-classification',
    SUB_DOMAIN VARCHAR COMMENT 'PRODUCTION, PETROPHYSICS, GENERAL',
    DOMAIN_NAME VARCHAR DEFAULT 'PRODUCTION',
    NAME VARCHAR NOT NULL COMMENT 'Short label',
    CONTENT VARCHAR NOT NULL COMMENT 'Full human-readable knowledge',
    CONTEXT_PROFILE VARCHAR COMMENT 'Enriched text for search indexing',
    SEMANTIC_VIEWS ARRAY COMMENT 'Semantic view names this applies to',
    PROPERTIES VARIANT COMMENT 'Structured metadata',
    CONFIDENCE FLOAT DEFAULT 1,
    PROMOTION_STATE VARCHAR DEFAULT 'none',
    ACTIVE_IND VARCHAR(1) DEFAULT 'Y',
    RETRIEVAL_COUNT NUMBER DEFAULT 0,
    LAST_RETRIEVED TIMESTAMP_NTZ,
    REMARK VARCHAR(2000),
    SOURCE VARCHAR(40),
    ROW_CREATED_BY VARCHAR(30) DEFAULT CURRENT_USER(),
    ROW_CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ROW_CHANGED_BY VARCHAR(30),
    ROW_CHANGED_DATE TIMESTAMP_NTZ,
    ROW_EFFECTIVE_DATE TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ROW_EXPIRY_DATE TIMESTAMP_NTZ,
    CONSTRAINT PK_PRODUCTION_DOMAIN_KNOWLEDGE PRIMARY KEY (ENTRY_ID)
) COMMENT = 'Domain knowledge store — synonyms, rules, metrics, column/table descriptions.';

-- NOTE: Domain knowledge entries must be seeded separately.
-- See the domain_knowledge_seed.sql file or populate from your own domain expertise.
-- The PRODUCTION_CONTEXT_SEARCH Cortex Search service (script 06) indexes this table.
