-- =============================================================================
-- PE_ASSISTANT: Production Engineering AI Advisor
-- Script 07: Semantic View — PRODUCTION_PERFORMANCE
-- =============================================================================
-- Run after: 04_curated_layer.sql (tables must be populated)
-- =============================================================================

USE SCHEMA PE_POC.CURATED;

CREATE OR REPLACE SEMANTIC VIEW PRODUCTION_PERFORMANCE
    COMMENT = 'Production performance analytics for the Volve oil field, combining daily well production data (rates, pressures, water cut, GOR) with petrophysical reservoir characterization (porosity, permeability, net-to-gross) to enable integrated production engineering analysis.'

    TABLES (
        PE_POC.CURATED.PRODUCTION_DAILY,
        PE_POC.CURATED.PETROPHYSICS_LOGS_TABLE,
        PE_POC.CURATED.PETROPHYSICS_WELL_SUMMARY_TABLE PRIMARY KEY (WELLBORE_NAME)
    )

    RELATIONSHIPS (
        PRODUCTION_DAILY_TO_PETROPHYSICS_WELL_SUMMARY_TABLE AS
            PRODUCTION_DAILY(WELLBORE_NAME) REFERENCES PETROPHYSICS_WELL_SUMMARY_TABLE(WELLBORE_NAME)
    )

    DIMENSIONS (
        PRODUCTION_DAILY.WELLBORE_CODE AS WELLBORE_CODE,
        PRODUCTION_DAILY.WELLBORE_NAME AS WELLBORE_NAME,
        PRODUCTION_DAILY.FIELD_NAME AS FIELD_NAME,
        PRODUCTION_DAILY.FACILITY_NAME AS FACILITY_NAME,
        PRODUCTION_DAILY.WELL_TYPE AS WELL_TYPE,
        PRODUCTION_DAILY.FLOW_KIND AS FLOW_KIND,
        PRODUCTION_DAILY.WELL_STATUS AS WELL_STATUS,
        PRODUCTION_DAILY.PRODUCTION_DATE AS PRODUCTION_DATE,
        PETROPHYSICS_LOGS_TABLE.WELLBORE_NAME AS WELLBORE_NAME,
        PETROPHYSICS_LOGS_TABLE.FIELD_NAME AS FIELD_NAME,
        PETROPHYSICS_LOGS_TABLE.NET_FLAG AS NET_FLAG,
        PETROPHYSICS_WELL_SUMMARY_TABLE.WELLBORE_NAME AS WELLBORE_NAME,
        PETROPHYSICS_WELL_SUMMARY_TABLE.TOTAL_SAMPLES AS TOTAL_SAMPLES,
        PETROPHYSICS_WELL_SUMMARY_TABLE.NET_SAMPLES AS NET_SAMPLES
    )

    FACTS (
        PRODUCTION_DAILY.ON_STREAM_HRS AS ON_STREAM_HRS,
        PRODUCTION_DAILY.AVG_CHOKE_PCT AS AVG_CHOKE_PCT,
        PRODUCTION_DAILY.AVG_DHP_BARA AS AVG_DHP_BARA,
        PRODUCTION_DAILY.AVG_WHP_BARA AS AVG_WHP_BARA,
        PRODUCTION_DAILY.AVG_ANNULUS_PRESS_BARA AS AVG_ANNULUS_PRESS_BARA,
        PRODUCTION_DAILY.DP_CHOKE_BARA AS DP_CHOKE_BARA,
        PRODUCTION_DAILY.AVG_DHT_DEGC AS AVG_DHT_DEGC,
        PRODUCTION_DAILY.AVG_WHT_DEGC AS AVG_WHT_DEGC,
        PRODUCTION_DAILY.OIL_VOL_SM3 AS OIL_VOL_SM3,
        PRODUCTION_DAILY.GAS_VOL_SM3 AS GAS_VOL_SM3,
        PRODUCTION_DAILY.WATER_VOL_SM3 AS WATER_VOL_SM3,
        PRODUCTION_DAILY.WATER_INJ_VOL_SM3 AS WATER_INJ_VOL_SM3,
        PRODUCTION_DAILY.WATER_CUT AS WATER_CUT,
        PRODUCTION_DAILY.GOR_SM3_SM3 AS GOR_SM3_SM3,
        PRODUCTION_DAILY.DRAWDOWN_BARA AS DRAWDOWN_BARA,
        PETROPHYSICS_LOGS_TABLE.MEASURED_DEPTH_M AS MEASURED_DEPTH_M,
        PETROPHYSICS_LOGS_TABLE.POROSITY AS POROSITY,
        PETROPHYSICS_LOGS_TABLE.WATER_SATURATION AS WATER_SATURATION,
        PETROPHYSICS_LOGS_TABLE.SHALE_VOLUME AS SHALE_VOLUME,
        PETROPHYSICS_LOGS_TABLE.PERMEABILITY_MD AS PERMEABILITY_MD,
        PETROPHYSICS_LOGS_TABLE.BULK_VOLUME_WATER AS BULK_VOLUME_WATER,
        PETROPHYSICS_LOGS_TABLE.CARBONATE_VOLUME AS CARBONATE_VOLUME,
        PETROPHYSICS_LOGS_TABLE.COAL_FLAG AS COAL_FLAG,
        PETROPHYSICS_LOGS_TABLE.SAND_FLAG AS SAND_FLAG,
        PETROPHYSICS_LOGS_TABLE.CARB_FLAG AS CARB_FLAG,
        PETROPHYSICS_LOGS_TABLE.HC_SATURATION AS HC_SATURATION,
        PETROPHYSICS_WELL_SUMMARY_TABLE.NET_TO_GROSS AS NET_TO_GROSS,
        PETROPHYSICS_WELL_SUMMARY_TABLE.MIN_DEPTH_M AS MIN_DEPTH_M,
        PETROPHYSICS_WELL_SUMMARY_TABLE.MAX_DEPTH_M AS MAX_DEPTH_M,
        PETROPHYSICS_WELL_SUMMARY_TABLE.AVG_POROSITY_NET AS AVG_POROSITY_NET,
        PETROPHYSICS_WELL_SUMMARY_TABLE.AVG_SW_NET AS AVG_SW_NET,
        PETROPHYSICS_WELL_SUMMARY_TABLE.AVG_VSH_NET AS AVG_VSH_NET,
        PETROPHYSICS_WELL_SUMMARY_TABLE.AVG_PERM_NET_MD AS AVG_PERM_NET_MD,
        PETROPHYSICS_WELL_SUMMARY_TABLE.MAX_PERM_NET_MD AS MAX_PERM_NET_MD,
        PETROPHYSICS_WELL_SUMMARY_TABLE.AVG_HC_SAT_NET AS AVG_HC_SAT_NET
    )

    AI_VERIFIED_QUERIES (
        "daily_production" AS (
            QUESTION 'What is the daily oil, gas, and water production by well over time for wells that are producing oil?'
            SQL 'SELECT WELLBORE_NAME, PRODUCTION_DATE, OIL_VOL_SM3, GAS_VOL_SM3, WATER_VOL_SM3, WATER_CUT, GOR_SM3_SM3 FROM production_daily WHERE OIL_VOL_SM3 > 0 ORDER BY PRODUCTION_DATE'
        ),
        "cumulative_vs_reservoir" AS (
            QUESTION 'How does cumulative production correlate with reservoir properties like porosity and permeability?'
            SQL 'SELECT p.WELLBORE_NAME, SUM(p.OIL_VOL_SM3) AS TOTAL_OIL, SUM(p.WATER_VOL_SM3) AS TOTAL_WATER, AVG(p.WATER_CUT) AS AVG_WATER_CUT, s.AVG_POROSITY_NET, s.AVG_PERM_NET_MD, s.NET_TO_GROSS FROM production_daily AS p JOIN petrophysics_well_summary_table AS s ON p.WELLBORE_NAME = s.WELLBORE_NAME GROUP BY p.WELLBORE_NAME, s.AVG_POROSITY_NET, s.AVG_PERM_NET_MD, s.NET_TO_GROSS'
        ),
        "pressure_drawdown" AS (
            QUESTION 'What is the pressure drawdown trend and its relationship to oil production rate across all wells over time?'
            SQL 'SELECT WELLBORE_NAME, PRODUCTION_DATE, AVG_DHP_BARA, AVG_WHP_BARA, DRAWDOWN_BARA, OIL_VOL_SM3 FROM production_daily WHERE NOT AVG_DHP_BARA IS NULL ORDER BY WELLBORE_NAME, PRODUCTION_DATE'
        ),
        "avg_performance" AS (
            QUESTION 'What is the average production performance for each producing well?'
            SQL 'SELECT WELLBORE_NAME, AVG(OIL_VOL_SM3) AS AVG_DAILY_OIL, AVG(WATER_CUT) AS AVG_WATER_CUT, AVG(GOR_SM3_SM3) AS AVG_GOR, COUNT(*) AS PRODUCING_DAYS FROM production_daily WHERE WELL_STATUS = ''PRODUCING'' GROUP BY WELLBORE_NAME'
        )
    );
